"""Deprecated legacy dialogue name extraction helpers.

Moved from speakers.py after the shift to NLTK-based person-name extraction.
Prefer `extract_person_names_from_text` instead. This module will be removed
in a future release.
"""

import logging
import re
import warnings

from english_words import get_english_words_set

from transcript_etl_pipeline.transform.name import Name

logger = logging.getLogger(__name__)

warnings.warn(
    "dialogue_names_deprecated is deprecated; use extract_person_names_from_text instead.",
    DeprecationWarning,
    stacklevel=2,
)

# English dictionary cache for legacy helpers
_english_words: set[str] | None = None

__all__ = [
    "_extract_names_from_dialogue",
    "_extract_title_case_chains",
    "_is_proper_noun",
    "_is_likely_person_name",
]


def _get_english_words() -> set[str]:  # pyright: ignore[reportUnusedFunction]
    """Get English words dictionary, loading it once and caching.

    Returns:
        Set of lowercase English words
    """
    global _english_words
    if _english_words is None:
        _english_words = get_english_words_set(["web2"], lower=True)
    return _english_words


def _extract_title_case_chains(text: str) -> list[tuple[str, int]]:
    """Extract chains of consecutive title-cased words from text.

    Identifies sequences of title-cased words (e.g., "Dan Moisan", "New York")
    and returns them as word groups along with their position.

    Args:
        text: The text to analyze

    Returns:
        List of tuples (word_group, start_position) where word_group is the
        space-joined title-cased words
    """
    # Pattern to match title-cased words
    title_case_pattern = r"\b[A-Z][a-z]+\b"

    chains: list[tuple[str, int]] = []
    words = list(re.finditer(title_case_pattern, text))

    if not words:
        return chains

    # Group consecutive title-cased words
    current_chain = [words[0]]

    for i in range(1, len(words)):
        prev_end = words[i - 1].end()
        curr_start = words[i].start()

        # Check if words are consecutive (only whitespace between)
        between = text[prev_end:curr_start]
        if between.strip() == "":
            current_chain.append(words[i])
        else:
            # Save current chain if it exists
            if current_chain:
                chain_text = " ".join(m.group() for m in current_chain)
                chains.append((chain_text, current_chain[0].start()))
            current_chain = [words[i]]

    # Don't forget the last chain
    if current_chain:
        chain_text = " ".join(m.group() for m in current_chain)
        chains.append((chain_text, current_chain[0].start()))

    return chains


def _is_proper_noun(word_group: str) -> bool:
    """Check if a word or word group is a proper noun.

    Enhanced logic:
    - Looks for title case chains (consecutive title-cased words are entities)
    - For single words, checks against English dictionary
    - Whitelists common first names that are in the dictionary
    - Word groups >3 tokens are rejected (unlikely to be names)

    Args:
        word_group: The word or phrase to check (may be multiple words)

    Returns:
        True if the word group appears to be a proper noun
    """
    if not word_group or not word_group.strip():
        return False

    tokens = word_group.strip().split()

    # Word groups >3 tokens are unlikely to be names
    if len(tokens) > 3:
        return False

    # All tokens must be title-cased
    for token in tokens:
        if len(token) < 2:
            return False
        if not token[0].isupper():
            return False
        if token.isupper():  # All caps (acronym)
            return False
        if not any(c.islower() for c in token):
            return False

    # For single-word groups, check if it's in the English dictionary
    # However, whitelist common first names that are in the dictionary
    if len(tokens) == 1:
        word_lower = tokens[0].lower()

        # Whitelist of common first names that should not be filtered
        # even though they're in the English dictionary
        common_first_names = {
            "dan",
            "john",
            "alice",
            "bob",
            "jane",
            "mary",
            "james",
            "michael",
            "david",
            "robert",
            "william",
            "richard",
            "joseph",
            "thomas",
            "charles",
            "christopher",
            "daniel",
            "matthew",
            "anthony",
            "mark",
            "donald",
            "steven",
            "paul",
            "andrew",
            "joshua",
            "kenneth",
            "kevin",
            "brian",
            "george",
            "edward",
            "ronald",
            "timothy",
            "jason",
            "jeffrey",
            "ryan",
            "jacob",
            "gary",
            "nicholas",
            "eric",
            "jonathan",
            "stephen",
            "larry",
            "justin",
            "scott",
            "brandon",
            "benjamin",
            "samuel",
            "frank",
            "gregory",
            "raymond",
            "patrick",
            "alexander",
            "jack",
            "dennis",
            "jerry",
            "tyler",
            "aaron",
            "jose",
            "henry",
            "adam",
            "douglas",
            "nathan",
            "peter",
            "zachary",
            "kyle",
            "walter",
            "harold",
            "jeremy",
            "ethan",
            "carl",
            "keith",
            "roger",
            "gerald",
            "christian",
            "terry",
            "sean",
            "arthur",
            "austin",
            "noah",
            "lawrence",
            "jesse",
            "joe",
            "bryan",
            "billy",
            "jordan",
            "albert",
            "dylan",
            "bruce",
            "willie",
            "gabriel",
            "logan",
            "alan",
            "juan",
            "ralph",
            "roy",
            "eugene",
            "randy",
            "vincent",
            "russell",
            "louis",
            "philip",
            "bobby",
            "johnny",
            "bradley",
            # Common female names
            "sarah",
            "jennifer",
            "lisa",
            "michelle",
            "nancy",
            "karen",
            "betty",
            "helen",
            "sandra",
            "donna",
            "carol",
            "ruth",
            "sharon",
            "laura",
            "kimberly",
            "deborah",
            "jessica",
            "shirley",
            "cynthia",
            "angela",
            "melissa",
            "brenda",
            "amy",
            "anna",
            "rebecca",
            "virginia",
            "kathleen",
            "pamela",
            "martha",
            "debra",
            "amanda",
            "stephanie",
            "carolyn",
            "christine",
            "marie",
            "janet",
            "catherine",
            "frances",
            "ann",
            "joyce",
            "diane",
            "julie",
            "heather",
            "teresa",
            "doris",
            "gloria",
            "evelyn",
            "jean",
            "cheryl",
            "mildred",
            "katherine",
            "joan",
            "ashley",
            "judith",
            "rose",
            "janice",
            "kelly",
            "nicole",
            "judy",
            "christina",
            "kathy",
            "theresa",
            "beverly",
            "denise",
            "tammy",
            "irene",
            "lori",
            "rachel",
            "marilyn",
            "andrea",
            "kathryn",
            "louise",
            "sara",
            "anne",
            "jacqueline",
            "wanda",
            "bonnie",
            "julia",
            "ruby",
            "lois",
            "tina",
            "phyllis",
            "norma",
            "paula",
            "diana",
            "annie",
            "lillian",
            "emily",
            "robin",
            "peggy",
            "crystal",
            "gladys",
            "rita",
            "dawn",
            "connie",
            "florence",
            "tracy",
            "edna",
            "tiffany",
            "carmen",
            "rosa",
            "cindy",
            "grace",
            "wendy",
            "victoria",
            "edith",
            "kim",
            "sherry",
            "sylvia",
            "josephine",
            "thelma",
            "shannon",
            "sheila",
            "ethel",
            "ellen",
            "elaine",
            "marjorie",
            "carrie",
            "charlotte",
            "monica",
            "esther",
            "pauline",
            "emma",
            "juanita",
            "anita",
            "rhonda",
            "hazel",
            "amber",
            "eva",
            "debbie",
            "april",
            "leslie",
            "clara",
            "lucille",
            "jamie",
            "joanne",
            "eleanor",
            "valerie",
            "danielle",
            "megan",
            "alicia",
            "suzanne",
            "michele",
            "gail",
            "bertha",
            "darlene",
            "veronica",
            "jill",
            "erin",
            "geraldine",
            "lauren",
            "cathy",
            "joann",
            "lorraine",
            "lynn",
            "sally",
            "regina",
            "erica",
            "beatrice",
            "dolores",
            "bernice",
            "audrey",
            "yvonne",
            "annette",
            "june",
            "samantha",
            "marion",
            "dana",
            "stacy",
            "ana",
            "renee",
            "ida",
            "vivian",
            "roberta",
            "holly",
            "brittany",
            "melanie",
            "loretta",
            "yolanda",
            "jeanette",
            "laurie",
            "katie",
            "kristen",
            "vanessa",
            "alma",
            "sue",
            "elsie",
            "beth",
            "jeanne",
            "vicki",
            "carla",
            "tara",
            "rosemary",
            "eileen",
            "terri",
            "gertrude",
            "lucy",
            "tonya",
            "ella",
            "stacey",
            "wilma",
            "gina",
            "kristin",
            "jessie",
            "natalie",
            "agnes",
            "vera",
            "charlene",
            "bessie",
            "delores",
            "melinda",
            "pearl",
            "arlene",
            "maureen",
            "colleen",
            "allison",
            "tamara",
            "joy",
            "georgia",
            "constance",
            "lillie",
            "claudia",
            "jackie",
            "marcia",
            "tanya",
            "nellie",
            "minnie",
            "marlene",
            "heidi",
            "glenda",
            "lydia",
            "viola",
            "courtney",
            "marian",
            "stella",
            "caroline",
            "dora",
            "jo",
            "vickie",
            "mattie",
            "maxine",
            "irma",
            "mabel",
            "marsha",
            "myrtle",
            "lena",
            "christy",
            "deanna",
            "patsy",
            "hilda",
            "gwendolyn",
            "jennie",
            "nora",
            "margie",
            "nina",
            "cassandra",
            "leah",
            "penny",
            "kay",
            "priscilla",
            "naomi",
            "carole",
            "brandy",
            "olga",
            "billie",
            "dianne",
            "tracey",
            "leona",
            "jenny",
            "felicia",
            "sonia",
            "miriam",
            "velma",
            "becky",
            "bobbie",
            "violet",
            "kristina",
            "toni",
            "misty",
            "mae",
            "shelly",
            "daisy",
            "ramona",
            "sherri",
            "erika",
            "katrina",
        }

        # If it's a common first name, treat it as a proper noun
        if word_lower in common_first_names:
            logger.debug(f"'{word_group}' is a whitelisted common first name")
            return True

        # Otherwise check against dictionary
        english_words = _get_english_words()
        english_words.add("okay")
        if word_lower in english_words:
            logger.debug(f"Skipping '{word_group}': found in English dictionary")
            return False

    return True


def _is_likely_person_name(word_group: str) -> bool:
    """Determine if a proper noun is likely a person name vs. place/thing.

    Enhanced logic:
    - Multi-token groups with English words are likely company names/titles
    - Exception: honorifics like "Mr.", "Mrs.", "Dr." are not company names
    - Single-token groups are checked against exclusion lists

    Args:
        word_group: The proper noun to classify (may be multiple words)

    Returns:
        True if the word group is likely a person name
    """
    tokens = word_group.strip().split()

    # Honorifics that indicate a person name follows
    honorifics = {"mr", "mrs", "ms", "dr", "prof", "sir", "dame", "lord", "lady"}

    # Whitelist of common first names (same as in _is_proper_noun)
    common_first_names = {
        "dan",
        "john",
        "alice",
        "bob",
        "jane",
        "mary",
        "james",
        "michael",
        "david",
        "robert",
        "william",
        "richard",
        "joseph",
        "thomas",
        "charles",
        "christopher",
        "daniel",
        "matthew",
        "anthony",
        "mark",
        "donald",
        "steven",
        "paul",
        "andrew",
        "joshua",
        "kenneth",
        "kevin",
        "brian",
        "george",
        "edward",
        "ronald",
        "timothy",
        "jason",
        "jeffrey",
        "ryan",
        "jacob",
        "gary",
        "nicholas",
        "eric",
        "jonathan",
        "stephen",
        "larry",
        "justin",
        "scott",
        "brandon",
        "benjamin",
        "samuel",
        "frank",
        "gregory",
        "raymond",
        "patrick",
        "alexander",
        "jack",
        "dennis",
        "jerry",
        "tyler",
        "aaron",
        "jose",
        "henry",
        "adam",
        "douglas",
        "nathan",
        "peter",
        "zachary",
        "kyle",
        "walter",
        "harold",
        "jeremy",
        "ethan",
        "carl",
        "keith",
        "roger",
        "gerald",
        "christian",
        "terry",
        "sean",
        "arthur",
        "austin",
        "noah",
        "lawrence",
        "jesse",
        "joe",
        "bryan",
        "billy",
        "jordan",
        "albert",
        "dylan",
        "bruce",
        "willie",
        "gabriel",
        "logan",
        "alan",
        "juan",
        "ralph",
        "roy",
        "eugene",
        "randy",
        "vincent",
        "russell",
        "louis",
        "philip",
        "bobby",
        "johnny",
        "bradley",
        # Common female names
        "sarah",
        "jennifer",
        "lisa",
        "michelle",
        "nancy",
        "karen",
        "betty",
        "helen",
        "sandra",
        "donna",
        "carol",
        "ruth",
        "sharon",
        "laura",
        "kimberly",
        "deborah",
        "jessica",
        "shirley",
        "cynthia",
        "angela",
        "melissa",
        "brenda",
        "amy",
        "anna",
        "rebecca",
        "virginia",
        "kathleen",
        "pamela",
        "martha",
        "debra",
        "amanda",
        "stephanie",
        "carolyn",
        "christine",
        "marie",
        "janet",
        "catherine",
        "frances",
        "ann",
        "joyce",
        "diane",
        "julie",
        "heather",
        "teresa",
        "doris",
        "gloria",
        "evelyn",
        "jean",
        "cheryl",
        "mildred",
        "katherine",
        "joan",
        "ashley",
        "judith",
        "rose",
        "janice",
        "kelly",
        "nicole",
        "judy",
        "christina",
        "kathy",
        "theresa",
        "beverly",
        "denise",
        "tammy",
        "irene",
        "lori",
        "rachel",
        "marilyn",
        "andrea",
        "kathryn",
        "louise",
        "sara",
        "anne",
        "jacqueline",
        "wanda",
        "bonnie",
        "julia",
        "ruby",
        "lois",
        "tina",
        "phyllis",
        "norma",
        "paula",
        "diana",
        "annie",
        "lillian",
        "emily",
        "robin",
        "peggy",
        "crystal",
        "gladys",
        "rita",
        "dawn",
        "connie",
        "florence",
        "tracy",
        "edna",
        "tiffany",
        "carmen",
        "rosa",
        "cindy",
        "grace",
        "wendy",
        "victoria",
        "edith",
        "kim",
        "sherry",
        "sylvia",
        "josephine",
        "thelma",
        "shannon",
        "sheila",
        "ethel",
        "ellen",
        "elaine",
        "marjorie",
        "carrie",
        "charlotte",
        "monica",
        "esther",
        "pauline",
        "emma",
        "juanita",
        "anita",
        "rhonda",
        "hazel",
        "amber",
        "eva",
        "debbie",
        "april",
        "leslie",
        "clara",
        "lucille",
        "jamie",
        "joanne",
        "eleanor",
        "valerie",
        "danielle",
        "megan",
        "alicia",
        "suzanne",
        "michele",
        "gail",
        "bertha",
        "darlene",
        "veronica",
        "jill",
        "erin",
        "geraldine",
        "lauren",
        "cathy",
        "joann",
        "lorraine",
        "lynn",
        "sally",
        "regina",
        "erica",
        "beatrice",
        "dolores",
        "bernice",
        "audrey",
        "yvonne",
        "annette",
        "june",
        "samantha",
        "marion",
        "dana",
        "stacy",
        "ana",
        "renee",
        "ida",
        "vivian",
        "roberta",
        "holly",
        "brittany",
        "melanie",
        "loretta",
        "yolanda",
        "jeanette",
        "laurie",
        "katie",
        "kristen",
        "vanessa",
        "alma",
        "sue",
        "elsie",
        "beth",
        "jeanne",
        "vicki",
        "carla",
        "tara",
        "rosemary",
        "eileen",
        "terri",
        "gertrude",
        "lucy",
        "tonya",
        "ella",
        "stacey",
        "wilma",
        "gina",
        "kristin",
        "jessie",
        "natalie",
        "agnes",
        "vera",
        "charlene",
        "bessie",
        "delores",
        "melinda",
        "pearl",
        "arlene",
        "maureen",
        "colleen",
        "allison",
        "tamara",
        "joy",
        "georgia",
        "constance",
        "lillie",
        "claudia",
        "jackie",
        "marcia",
        "tanya",
        "nellie",
        "minnie",
        "marlene",
        "heidi",
        "glenda",
        "lydia",
        "viola",
        "courtney",
        "marian",
        "stella",
        "caroline",
        "dora",
        "jo",
        "vickie",
        "mattie",
        "maxine",
        "irma",
        "mabel",
        "marsha",
        "myrtle",
        "lena",
        "christy",
        "deanna",
        "patsy",
        "hilda",
        "gwendolyn",
        "jennie",
        "nora",
        "margie",
        "nina",
        "cassandra",
        "leah",
        "penny",
        "kay",
        "priscilla",
        "naomi",
        "carole",
        "brandy",
        "olga",
        "billie",
        "dianne",
        "tracey",
        "leona",
        "jenny",
        "felicia",
        "sonia",
        "miriam",
        "velma",
        "becky",
        "bobbie",
        "violet",
        "kristina",
        "toni",
        "misty",
        "mae",
        "shelly",
        "daisy",
        "ramona",
        "sherri",
        "erika",
        "katrina",
    }

    # Whitelist of common last names that are also in the dictionary
    common_last_names = {
        "smith",
        "johnson",
        "williams",
        "jones",
        "brown",
        "davis",
        "miller",
        "wilson",
        "moore",
        "taylor",
        "anderson",
        "thomas",
        "jackson",
        "white",
        "harris",
        "martin",
        "thompson",
        "garcia",
        "martinez",
        "robinson",
        "clark",
        "rodriguez",
        "lewis",
        "lee",
        "walker",
        "hall",
        "allen",
        "young",
        "hernandez",
        "king",
        "wright",
        "lopez",
        "hill",
        "scott",
        "green",
        "adams",
        "baker",
        "gonzalez",
        "nelson",
        "carter",
        "mitchell",
        "perez",
        "roberts",
        "turner",
        "phillips",
        "campbell",
        "parker",
        "evans",
        "edwards",
        "collins",
        "stewart",
        "sanchez",
        "morris",
        "rogers",
        "reed",
        "cook",
        "morgan",
        "bell",
        "murphy",
        "bailey",
        "rivera",
        "cooper",
        "richardson",
        "cox",
        "howard",
        "ward",
        "torres",
        "peterson",
        "gray",
        "ramirez",
        "james",
        "watson",
        "brooks",
        "kelly",
        "sanders",
        "price",
        "bennett",
        "wood",
        "barnes",
        "ross",
        "henderson",
        "coleman",
        "jenkins",
        "perry",
        "powell",
        "long",
        "patterson",
        "hughes",
        "flores",
        "washington",
        "butler",
        "simmons",
        "foster",
        "gonzales",
        "bryant",
        "alexander",
        "russell",
        "griffin",
        "diaz",
        "hayes",
        "myers",
        "ford",
        "hamilton",
        "graham",
        "sullivan",
        "wallace",
        "woods",
        "cole",
        "west",
        "jordan",
        "owens",
        "reynolds",
        "fisher",
        "ellis",
        "harrison",
        "gibson",
        "mcdonald",
        "cruz",
        "marshall",
        "ortiz",
        "gomez",
        "murray",
        "freeman",
        "wells",
        "webb",
        "simpson",
        "stevens",
        "tucker",
        "porter",
        "hunter",
        "hicks",
        "crawford",
        "henry",
        "boyd",
        "mason",
        "morales",
        "kennedy",
        "warren",
        "dixon",
        "ramos",
        "reyes",
        "burns",
        "gordon",
        "shaw",
        "holmes",
        "rice",
        "robertson",
        "hunt",
        "black",
        "daniels",
        "palmer",
        "mills",
        "nichols",
        "grant",
        "knight",
        "ferguson",
        "rose",
        "stone",
        "hawkins",
        "dunn",
        "perkins",
        "hudson",
        "spencer",
        "gardner",
        "stephens",
        "payne",
        "pierce",
        "berry",
        "matthews",
        "arnold",
        "wagner",
        "willis",
        "ray",
        "watkins",
        "olson",
        "carroll",
        "duncan",
        "snyder",
        "hart",
        "cunningham",
        "bradley",
        "lane",
        "andrews",
        "ruiz",
        "harper",
        "fox",
        "riley",
        "armstrong",
        "carpenter",
        "weaver",
        "greene",
        "lawrence",
        "elliott",
        "chavez",
        "sims",
        "austin",
        "peters",
        "kelley",
        "franklin",
        "lawson",
        "fields",
        "gutierrez",
        "ryan",
        "schmidt",
        "carr",
        "vasquez",
        "castillo",
        "wheeler",
        "chapman",
        "oliver",
        "montgomery",
        "richards",
        "williamson",
        "johnston",
        "banks",
        "meyer",
        "bishop",
        "mccoy",
        "howell",
        "alvarez",
        "morrison",
        "hansen",
        "fernandez",
        "garza",
        "harvey",
        "little",
        "burton",
        "stanley",
        "nguyen",
        "george",
        "jacobs",
        "reid",
        "kim",
        "fuller",
        "lynch",
        "dean",
        "gilbert",
        "garrett",
        "romero",
        "welch",
        "larson",
        "frazier",
        "burke",
        "hanson",
        "day",
        "mendoza",
        "moreno",
        "bowman",
        "medina",
        "fowler",
        "brewer",
        "hoffman",
        "carlson",
        "silva",
        "pearson",
        "holland",
        "douglas",
        "fleming",
        "jensen",
        "vargas",
        "byrd",
        "davidson",
        "hopkins",
        "may",
        "terry",
        "herrera",
        "wade",
        "soto",
        "walters",
        "curtis",
        "neal",
        "caldwell",
        "lowe",
        "jennings",
        "barnett",
        "graves",
        "jimenez",
        "horton",
        "shelton",
        "barrett",
        "obrien",
        "castro",
        "sutton",
        "gregory",
        "mckinney",
        "lucas",
        "miles",
        "craig",
        "rodriquez",
        "chambers",
        "holt",
        "lambert",
        "fletcher",
        "watts",
        "bates",
        "hale",
        "rhodes",
        "pena",
        "beck",
        "newman",
        "haynes",
        "mcdaniel",
        "mendez",
        "bush",
        "vaughn",
        "parks",
        "dawson",
        "santiago",
        "norris",
        "hardy",
        "love",
        "steele",
        "curry",
        "powers",
        "schultz",
        "barker",
        "guzman",
        "page",
        "munoz",
        "ball",
        "keller",
        "chandler",
        "weber",
        "leonard",
        "walsh",
        "lyons",
        "ramsey",
        "wolfe",
        "schneider",
        "mullins",
        "benson",
        "sharp",
        "bowen",
        "daniel",
        "barber",
        "cummings",
        "hines",
        "baldwin",
        "griffith",
        "valdez",
        "hubbard",
        "salazar",
        "reeves",
        "warner",
        "stevenson",
        "burgess",
        "santos",
        "tate",
        "cross",
        "garner",
        "mann",
        "mack",
        "moss",
        "thornton",
        "dennis",
        "mcgee",
        "farmer",
        "delgado",
        "aguilar",
        "vega",
        "glover",
        "manning",
        "cohen",
        "harmon",
        "rodgers",
        "robbins",
        "newton",
        "todd",
        "blair",
        "higgins",
        "ingram",
        "reese",
        "cannon",
        "strickland",
        "townsend",
        "potter",
        "goodman",
        "walton",
        "rowe",
        "hampton",
        "ortega",
        "patton",
        "swanson",
        "joseph",
        "francis",
        "goodwin",
        "maldonado",
        "yates",
        "becker",
        "erickson",
        "hodges",
        "rios",
        "conner",
        "adkins",
        "webster",
        "norman",
        "malone",
        "hammond",
        "flowers",
        "cobb",
        "moody",
        "quinn",
        "blake",
        "maxwell",
        "pope",
        "floyd",
        "osborne",
        "paul",
        "mccarthy",
        "guerrero",
        "lindsey",
        "estrada",
        "sandoval",
        "gibbs",
        "tyler",
        "gross",
        "fitzgerald",
        "stokes",
        "doyle",
        "sherman",
        "saunders",
        "wise",
        "colon",
        "gill",
        "alvarado",
        "greer",
        "padilla",
        "simon",
        "waters",
        "nunez",
        "ballard",
        "schwartz",
        "mcbride",
        "houston",
        "christensen",
        "klein",
        "pratt",
        "briggs",
        "parsons",
        "mclaughlin",
        "zimmerman",
        "french",
        "buchanan",
        "moran",
        "copeland",
        "roy",
        "pittman",
        "brady",
        "mccormick",
        "holloway",
        "brock",
        "poole",
        "frank",
        "logan",
        "owen",
        "bass",
        "marsh",
        "drake",
        "wong",
        "jefferson",
        "park",
        "morton",
        "abbott",
        "sparks",
        "patrick",
        "norton",
        "huff",
        "clayton",
        "massey",
        "lloyd",
        "figueroa",
        "carson",
        "bowers",
        "roberson",
        "barton",
        "tran",
        "lamb",
        "harrington",
        "casey",
        "boone",
        "cortez",
        "clarke",
        "mathis",
        "singleton",
        "wilkins",
        "cain",
        "bryan",
        "underwood",
        "hogan",
        "mckenzie",
        "collier",
        "luna",
        "phelps",
        "mcguire",
        "allison",
        "bridges",
        "wilkerson",
        "nash",
        "summers",
        "atkins",
    }

    # Check if multi-token group contains English words
    # This likely indicates a company name or title
    # Exception: Common first/last names are whitelisted
    if len(tokens) > 1:
        english_words = _get_english_words()

        # Check each token (excluding honorifics and common names)
        for token in tokens:
            token_lower = token.lower().rstrip(".")

            # Skip honorifics
            if token_lower in honorifics:
                continue

            # Skip common first/last names (whitelisted)
            if token_lower in common_first_names or token_lower in common_last_names:
                continue

            # If we find an English word (not a name), it's likely a company/title
            if token_lower in english_words:
                logger.debug(f"Skipping '{word_group}': multi-token with English word '{token}'")
                return False

    # For single tokens, check exclusion lists
    if len(tokens) == 1:
        word_lower = tokens[0].lower()

        # Common places to exclude
        places = {
            "america",
            "north",
            "south",
            "east",
            "west",
            "africa",
            "asia",
            "europe",
            "australia",
            "canada",
            "mexico",
            "california",
            "texas",
            "florida",
            "york",
            "london",
            "paris",
            "tokyo",
            "beijing",
            "moscow",
            "boston",
            "chicago",
            "seattle",
            "atlanta",
            "denver",
            "portland",
            "austin",
        }

        # Temporal words to exclude
        temporal = {
            "monday",
            "tuesday",
            "wednesday",
            "thursday",
            "friday",
            "saturday",
            "sunday",
            "january",
            "february",
            "march",
            "april",
            "may",
            "june",
            "july",
            "august",
            "september",
            "october",
            "november",
            "december",
        }

        # Organizations/products to exclude
        organizations = {
            "microsoft",
            "apple",
            "google",
            "amazon",
            "facebook",
            "twitter",
            "linkedin",
            "github",
            "windows",
            "linux",
            "android",
            "iphone",
            "internet",
            "email",
        }

        if word_lower in places or word_lower in temporal or word_lower in organizations:
            logger.debug(f"Skipping '{word_group}': in exclusion list")
            return False

    return True


def _extract_names_from_dialogue(text: str) -> set[Name]:
    """Deprecated: use extract_person_names_from_text instead.

    Extract names mentioned in dialogue through direct address patterns.

    Enhanced to properly identify proper nouns and distinguish between
    person names vs. places/things. Uses title case chain detection to
    identify multi-word names.

    Only extracts names from clear direct address contexts like:
    - "Hi, Dan"
    - "Thanks, Anne"
    - "Dan, what do you think?"
    - "Hi, Dan Moisan" (multi-word names)

    The function:
    1. Extracts title case chains (e.g., "Dan Moisan", "New York")
    2. Checks if each chain is a proper noun (English dictionary check)
    3. Filters out places, organizations, and common words
    4. Only captures words/chains that are likely person names

    Args:
        text: The text to analyze

    Returns:
        Set of Name objects mentioned in direct address
    """
    warnings.warn(
        "_extract_names_from_dialogue is deprecated; use extract_person_names_from_text instead.",
        DeprecationWarning,
        stacklevel=2,
    )
    names: set[Name] = set()

    # Direct address patterns - capturing one or more title-cased words (non-greedy)
    # Use [ ] instead of \s to prevent matching across lines (\s includes \r and \n)
    # Pattern captures consecutive title-cased words up to 3 words
    name_pattern = r"[A-Z][a-z]+(?:[ ][A-Z][a-z]+){0,2}"

    patterns = [
        rf"(?:Hi|Hey|Hello|Thanks|Thank you),[ ]+({name_pattern})",  # "Hi, Dan"
        rf"(?:Hi|Hey|Hello|Thanks|Thank you)[ ]+({name_pattern})",  # "Hello Alice"
        rf"\b({name_pattern}),[ ]+(?:what|how|can|could|would|do|did|thanks)",  # "Dan, what..."
        rf"(?:As|So)[ ]+({name_pattern})[ ]+(?:mentioned|said|noted)",  # "As Dan mentioned"
        rf"(?i)(?:how|where)[ ]+is[ ]+({name_pattern})",  # "How is Alice?"
    ]

    for pattern in patterns:
        matches = re.findall(pattern, text, re.MULTILINE)
        for match in matches:
            match = match.strip()

            # Skip if match contains newlines (captured across lines)
            if "\r" in match or "\n" in match:
                continue

            # First check: Must be a proper noun (checks dictionary for single words)
            if not _is_proper_noun(match):
                continue

            # Second check: Must be likely a person name (not place/thing/company)
            if not _is_likely_person_name(match):
                continue

            # Passed all checks, create Name object
            logger.debug(f"Extracted name from dialogue: {match}")
            try:
                # Parse multi-word names properly
                name = Name.from_string(match)
                names.add(name)
            except ValueError:
                logger.debug(f"Skipping invalid name: {match}")

    return names
