[CmdletBinding()]
param(
    [string]$RepoRoot = (Resolve-Path "$PSScriptRoot/../..")
)

$sections = @(
    @{ Key = "general-code-change"; Title = "General Code Change Policy"; FileName = "general-code-change.instructions.md" },
    @{ Key = "general-unit-test"; Title = "General Unit Test Policy"; FileName = "general-unit-test.instructions.md" },
    @{ Key = "github-actions"; Title = "GitHub Actions Workflow Policy"; FileName = "github-actions.instructions.md" },
    @{ Key = "python-code-change"; Title = "Python Code Change Policy"; FileName = "python-code-change.instructions.md" },
    @{ Key = "python-unit-test"; Title = "Python Unit Test Policy"; FileName = "python-unit-test.instructions.md" },
    @{ Key = "python-noqa"; Title = "Python Suppression Policy (noqa and type: ignore)"; FileName = "python-suppressions.instructions.md" },
    @{ Key = "powershell-code-change"; Title = "PowerShell Code Change Policy"; FileName = "powershell-code-change.instructions.md" },
    @{ Key = "powershell-unit-test"; Title = "PowerShell Unit Test Policy"; FileName = "powershell-unit-test.instructions.md" },
    @{ Key = "codexer"; Title = "Codexer Policy"; FileName = "codexer.instructions.md" },
    @{ Key = "self-explanatory-code-commenting"; Title = "Code Commenting and Docstring Policy"; FileName = "self-explanatory-code-commenting.instructions.md" }
)

function Get-InstructionsBody {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Instructions file not found: $Path"
    }

    $content = Get-Content -Raw -LiteralPath $Path

    if ($content -match '^\s*---\s*[\s\S]*?---\s*') {
        $content = $content -replace '^\s*---\s*[\s\S]*?---\s*', ''
    }

    return $content.Trim()
}

function Get-AgentContent {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepoRootParam
    )

    $instructionsDirPath = Join-Path $RepoRootParam ".github/instructions"
    $copilotPath = Join-Path $RepoRootParam ".github/copilot-instructions.md"
    $agentsTarget = Join-Path $RepoRootParam "AGENTS.md"

    $copilotBody = Get-InstructionsBody -Path $copilotPath

    $copilotSection = @"
## Repository Instructions (GitHub Copilot Canonical)

<!-- BEGIN: copilot-instructions -->
$copilotBody

<!-- END: copilot-instructions -->

"@

    $sectionBlocks = foreach ($section in $sections) {
        $filePath = Join-Path $instructionsDirPath $section.FileName
        $body = Get-InstructionsBody -Path $filePath

        @"
## $($section.Title)

<!-- BEGIN: $($section.Key) -->
$body

<!-- END: $($section.Key) -->

"@
    }

    $header = @"
# AGENTS.md

> NOTE: This file is **generated** from:
>
> - .github/copilot-instructions.md
> - .github/instructions/general-code-change.instructions.md
> - .github/instructions/general-unit-test.instructions.md
> - .github/instructions/github-actions.instructions.md
> - .github/instructions/python-code-change.instructions.md
> - .github/instructions/python-unit-test.instructions.md
> - .github/instructions/python-suppressions.instructions.md
> - .github/instructions/powershell-code-change.instructions.md
> - .github/instructions/powershell-unit-test.instructions.md
>
> Do not edit this file manually.
> To update policies, edit the source *.instructions.md files and
> `.github/copilot-instructions.md`, then run:
>
>   pwsh -File scripts/dev-tools/sync-agents-from-instructions.ps1

## Repository Setup (High-Level)

- For coding and testing policies, always follow the sections below in the order:
  Copilot instructions → general policies → language-specific policies → CI policies.
- Use the language- and domain-specific sections for Python, PowerShell, and CI behavior.
"@

    $agentsContent = $header + "`n`n" + $copilotSection + "`n" + ($sectionBlocks -join "`n")

    return [pscustomobject]@{ Path = $agentsTarget; Content = $agentsContent }
}

function Invoke-SyncAgentInstruction {
    [CmdletBinding(SupportsShouldProcess = $true)]
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepoRootParam
    )

    $result = Get-AgentContent -RepoRootParam $RepoRootParam
    if (-not $PSCmdlet.ShouldProcess($result.Path, 'Update AGENTS.md')) {
        return
    }

    Set-Content -LiteralPath $result.Path -Value $result.Content -NoNewline
    Write-Output "Updated $($result.Path) from .github/copilot-instructions.md and .github/instructions/*.instructions.md"
}

if ($MyInvocation.InvocationName -eq '.') {
    return
}

if ($env:POSHQC_SKIP_SCRIPT_EXECUTION) {
    return
}

Invoke-SyncAgentInstruction -RepoRootParam $RepoRoot






